config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  post 'new_dose', to: 'pages#new_dose'
  delete 'delete_all_doses', to: 'pages#delete_all_doses'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :user
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :doses
  has_many :ingredients, through: :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!, only: [:home, :delete_all_doses, :new_dose]

  def about
  end

  def contact
  end

  def home
    @ingredients = Ingredient.all
    @doses = Dose.all
    summary
  end

  def new_dose
    @dose = Dose.new(ingredient_id: params[:ingredient], amount: params[:amount], user_id: 1)
    @dose.save!
    redirect_to root_path
  end

  def summary
    doses = Dose.all
    summary_price = 0
    summary_weight = 0
    summary_protein = 0
    doses.each do |dose|
      summary_price += dose.ingredient.price
      summary_weight += dose.ingredient.weight
      summary_protein += dose.ingredient.protein
    end
    @summary_price = summary_price
    @summary_weight = summary_weight
    @summary_protein = summary_protein
    render 'pages/home'
  end

  def delete_all_doses
    @doses = Dose.all
    @doses.destroy_all

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zweiloeffel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>We are</h1>

app/views/pages/contact.html.erb
<h1>Here</h1>

app/views/pages/home.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
    </div>
    <div class="col-md-4">
      <div class="row pl-3 mt-3">
        <div class="col-md-4">
          <div class="row">
            <h4>Preis: &nbsp;</h4><h4 id="finalPrice">0</h4><h4> &nbsp;€</h4>
          </div>
        </div>
        <div class="col-md-4">
          <div class="row">
            <h4>Gewicht: &nbsp;</h4><h4 id="finalWeight">0</h4><h4> &nbsp;g</h4>
          </div>
        </div>
        <div class="col-md-4">
          <div class="pl-2">
            <%= button_to "Kaufen", delete_all_doses_path, method: "delete", remote:true, class: "btn btn-success btn-lg", style: "float:right;"%>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="row" id="ingredientSelection">
          <% @ingredients.each do |ingredient| %>
            <div class="col-md-3 p-3" id= <%= ingredient.name %>>
                <%= render 'shared/card_ingredient', ingredient_within: ingredient %>
            </div>


          <% end %>

      </div>
    </div>
    <div style="transform: rotate(180deg);" class="col-md-4 p-3">
      <%= render 'shared/jar' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2 text-center" >
      <%= render 'shared/pie-chart', summary_protein_within: @summary_protein, remote: true %>
      <p id="finalProtein"></p><p> Gramm </p>
    </div>
    <div class="col-md-2">
      <p id="target"></p>
    </div>
    <div class="col-md-2">
    </div>
    <div class="col-md-2">
    </div>
    <div class="col-md-2">
    </div>
    <div class="col-md-2">
      <%= button_to "Restart", delete_all_doses_path, method: "delete", remote:true, class: "btn btn-danger btn-lg", style: "float:right;"%>
    </div>
  </div>
</div>



<!-- Primal structure -->
<!-- <div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
    </div>
    <div class="col-md-4">
      <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-3">
        </div>
        <div class="col-md-3">
        </div>
        <div class="col-md-3">
        </div>
      </div>
    </div>
    <div class="col-md-4">
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-2">
    </div>
    <div class="col-md-2">
    </div>
    <div class="col-md-2">
    </div>
    <div class="col-md-2">
    </div>
    <div class="col-md-2">
    </div>
  </div>
</div> -->

app/views/shared/_card_ingredient.html.erb
<!-- <%#= link_to new_dose_path(ingredient: ingredient_within.id, amount: 10), method: :post, remote:  true  do %> -->
  <div class="selectionCard"
    data-name="<%= ingredient_within.name %>"
    data-weight="<%= ingredient_within.weight %>"
    data-price="<%= ingredient_within.price %>"
    data-protein="<%= ingredient_within.protein %>"
    data-img="<%= ingredient_within.img %>">
    <img src=<%= ingredient_within.img %> />
    <div class="selectionCard-infos">
      <div>
        <h2><%= ingredient_within.name %></h2>
        <p>Protein: <%= ingredient_within.protein %> Gramm</p>
      </div>
      <h2 class="selectionCard-pricing"><%= ingredient_within.price %>€</h2>
    </div>
  </div>

  <script>

   // document.getElementById("<%#= ingredient_within.name %>").addEventListener("click", increaseOrder);
    // function increaseOrder() {
    //   let currentSelection = event.path[2].id;
    //   console.log(event.path[2].id);
    //   // Increase price
    //   price += <%#= ingredient_within.price %>
    //   document.getElementById("price").innerHTML = price;
    //   // Increase weight
    //   weight += <%#= ingredient_within.weight %>
    //   document.getElementById("weight").innerHTML = weight;
    //   // Increase protein
    //   protein += <%#= ingredient_within.protein %>
    //   document.getElementById("protein").innerHTML = protein;
      // }
  </script>
<%# end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_jar.html.erb
<!-- <div class="jar">
    <div class="row p-0 m-0">
      <div class="col-md-12 --0 m-0">
      </div>
      <div class="col-md-12 --0 m-0">
      </div>
      <div class="col-md-12 --0 m-0">
      </div>
      <div class="col-md-12 --0 m-0">
      </div>
      <div class="col-md-12 --0 m-0">
      </div>
      <div class="col-md-12 --0 m-0">
      </div>
      <div class="col-md-12 --0 m-0">
      </div>
      <div class="col-md-12 --0 m-0 p-0 m-0">
      </div>
    </div>
</div> -->

<div id="jar" style="height: 604px;" class="jar-container">
  <div id="jar-content-div-0">
    <div class="jar-content" id="jar-content-0" >
      <img style="height: 0px; display: block;"class="ingredient-jar" data-jarname=" " id="jar-img-0" src=" " alt="">
    </div>
  </div>
  <div id="jar-content-div-1">
    <div class="jar-content" id="jar-content-1" >
      <img style="height: 0px; display: block;"class="ingredient-jar" data-jarname=" " id="jar-img-1" src=" " alt="">
    </div>
  </div>
  <div id="jar-content-div-2">
    <div class="jar-content" id="jar-content-2" >
      <img style="height: 0px; display: block;"class="ingredient-jar" data-jarname=" " id="jar-img-2" src=" " alt="">
    </div>
  </div>
  <div id="jar-content-div-3">
    <div class="jar-content" id="jar-content-3" >
      <img style="height: 0px; display: block;"class="ingredient-jar" data-jarname=" " id="jar-img-3" src=" " alt="">
    </div>
  </div>
  <div id="jar-content-div-4">
    <div class="jar-content" id="jar-content-4" >
      <img style="height: 0px; display: block;"class="ingredient-jar" data-jarname=" " id="jar-img-4" src=" " alt="">
    </div>
  </div>
  <div id="jar-content-div-5">
    <div class="jar-content" id="jar-content-5" >
      <img style="height: 0px; display: block;"class="ingredient-jar" data-jarname=" " id="jar-img-5" src=" " alt="">
    </div>
  </div>
  <div id="jar-content-div-6">
    <div class="jar-content" id="jar-content-6" >
      <img style="height: 0px; display: block;"class="ingredient-jar" data-jarname=" " id="jar-img-6" src=" " alt="">
    </div>
  </div>
  <div id="jar-content-div-7">
    <div class="jar-content" id="jar-content-7" >
      <img style="height: 0px; display: block;"class="ingredient-jar" data-jarname=" " id="jar-img-7" src=" " alt="">
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dj9iphc8u/image/upload/v1626981858/spoons_gawx9o.png" %>
    <% end %>
    <h3 style="padding: 0; margin: 0; font-size: xxx-large;">2Löffel</h3>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_pie-chart.html.erb
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<canvas id="myChart" data-turbolinks="true"></canvas>